### ISSUE TITLE
Unable to merge PR due to commit signature

### ISSUE THREAD

**Issue by miguelnietoa** [step-security/secure-repo#1718]
Hi there 👋🏻 

GitHub has a rule that requires commits to be signed.  

Seems like this PR contains commits that are not signed, and therefore I am unable to merge it. Although it has `Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>` in the commit description. 🤔 

Not sure why GitHub doesn't recognize it as a verified commit.

PR: https://github.com/kommitters/stellar_sdk/pull/264

 ⬇️ Notice the last text ❌ **Merging is blocked**  

![image](https://user-images.githubusercontent.com/39246879/209166917-027d000c-0cef-4210-9960-ca75d1ee3c6e.png)

**Comment by miguelnietoa** [comment]
I will merge the PR however it would be good to investigate why what I said is happening!

I look forward to any updates or interest around this. 👍🏻

**Comment by varunsh-coder** [comment]
Thanks, @miguelnietoa, for creating the issue! I think this is happening because the commits are not signed using GPG, SSH, or S/MIME. https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

We will investigate how to do this for the bot and get back. 

CC: @boahc077

**Comment by miguelnietoa** [comment]
Yes @varunsh-coder, that's why! 👍🏻 Thanks a lot

**Comment by varunsh-coder** [comment]
This issue is resolved. Here is an example. Please re-open if you see an issue with the fix. 
https://github.com/dhurley/github-actions-playground/pull/4
